### ISSUE TITLE
Add visual monitor

### ISSUE THREAD

**Issue by amitaibu** [Gizra-Shoov/robo-team#1]
http://www.robo-team.com/

**Comment by DavidKohav** [comment]
![ct8uyopu8ae01rt1140](https://cloud.githubusercontent.com/assets/5812423/12644777/16518c72-c5ce-11e5-85da-ad149eb3ada6.jpg)

**Comment by mldk-tech** [comment]
https://app.shoov.io/#/screenshots/22117

**Comment by mldk-tech** [comment]
http://gfycat.com/DisfiguredClumsyBluebottlejellyfish
